### PR TITLE
Remove depreceted calls to prepare for symfony 3.0

### PR DESCRIPTION
**Pull request by NoUseFreak**

### CODE REVIEW

**Comment by chteuchteu** [comment]
This PR is actually a "light" version of [mine](https://github.com/egeloen/ivory-ordered-form/pull/11). Note to the contributor: this one may not need as much work as mine to be merged and maintained, so you may want to merge this one instead of mine

**Comment by NoUseFreak** [comment]
@chteuchteu Darn, I missed your version. 
@egeloen Let me know what to do with this one as it is indeed a duplicate of #11

**Comment by chteuchteu** [comment]
@NoUseFreak No problem! We should keep the one that's closest to the desired behavior. I don't think that either of our PR can be used as-is (since they break Travis CI)

**Comment by NoUseFreak** [comment]
I was searching for a way to increase the minimum version to the minimum working version as it is broken with --prefer-lowest. But I haven't found the time yet, I might try it later today.

**Comment by egeloen** [comment]
Closing in favor of #13

**Pull request closed without merging**
